---
- hosts: webservers
  become: yes
  tasks:
    - name: Remove Docker container
      docker_container:
        name: ecommerce
        state: absent

    - name: Remove Docker image
      docker_image:
        name: ecommerce
        state: absent

    - name: Build Docker image
      docker_image:
        path: "/home/namanv2/"
        name: ecommerce
        source: build

    - name: Run Docker container
      docker_container:
        name: ecommerce
        image: ecommerce
        published_ports:
          - "8080:8080"
